spring.application.name: eureka-server

---
spring:
  profiles: eureka-peer1
server.port: 8761
eureka:
  instance:
    hostname: eureka-peer1
    metadataMap:
      zone: us-central
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    preferSameZoneEureka: true
    healthcheck:
      enabled: false
  datacenter: chicago
  environment: production

---
spring:
  profiles: eureka-peer2
server.port: 8762
eureka:
  instance:
    hostname: eureka-peer2
    metadataMap:
      zone: us-central
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    preferSameZoneEureka: true
    healthcheck:
      enabled: false
  datacenter: chicago
  environment: production
